changelog:
  categories:
    - title: Test
      labels:
        - test
    - title: Features
      labels:
        - "major features"
        - "minor features"
    - title: Experimental Features
      labels:
        - experimental
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - ignore for release
      - contributing
      - continuous integration
