language: c

env:
  - PYTHON_VERSION="2"
  - PYTHON_VERSION="3"

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# Turn off email notifications
notifications:
  email: false

os:
  - linux
  - osx

install:
  - cd ..
  - mv tethys src
  - bash ./src/scripts/install_tethys.sh -h
  - bash ./src/scripts/install_tethys.sh --partial-tethys-install mesdat -t $PWD --python-version $PYTHON_VERSION
  - pwd
  - ls ./miniconda/bin/
  - source ./miniconda/bin/activate tethys
  - rm ./src/tethys_portal/settings.py
  - bash ./src/scripts/install_tethys.sh --partial-tethys-install s -t $PWD --db-username tethys_super
  - tstartdb
  - conda list
  - cat $CONDA_HOME/envs/tethys/etc/conda/activate.d/tethys-activate.sh

# command to run tests
script:
  - tethys test
  - tstart


# generate test coverage information
# after_success:
  # coveralls
