name: tethys
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bokeh=0.12.3=py27_0
- cffi=1.7.0=py27_0
- cryptography=1.5=py27_0
- enum34=1.1.6=py27_0
- futures=3.0.5=py27_0
- idna=2.1=py27_0
- ipaddress=1.0.16=py27_0
- jinja2=2.8=py27_1
- libffi=3.2.1=0
- markupsafe=0.23=py27_2
- mkl=11.3.3=0
- numpy=1.11.2=py27_0
- openssl=1.0.2h=1
- pandas=0.19.1=np111py27_0
- pip=8.1.2=py27_0
- plotly=1.12.9=py27_0
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_1
- pyopenssl=16.0.0=py27_0
- python=2.7.12=1
- python-dateutil=2.6.0=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- setuptools=26.1.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - azure==0.10.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - boto==2.25.0
  - condorpy==0.2.0
  - decorator==3.4.0
  - django==1.9.9
  - django-bootstrap3==6.2.2
  - django-gravatar2==1.4.0
  - django-guardian==1.4.6
  - django-model-utils==2.4
  - django-termsandconditions==1.1.9
  - docker-py==1.2.3
  - ecdsa==0.13
  - geoalchemy2==0.2.6
  - gisdata==0.5.4
  - gsconfig==1.0.6
  - gsshapy==2.0.0
  - httplib2==0.9.2
  - iptools==0.6.1
  - iso8601==0.1.8
  - mapkit==1.1.0
  - oauthlib==2.0.0
  - optcomplete===1.2-devel
  - owslib==0.8.13
  - paramiko==1.15.2
  - paste==1.7.5.1
  - pastedeploy==1.5.2
  - pastescript==1.7.5
  - psycopg2==2.6.2
  - pycrypto==2.6.1
  - pyjwt==1.4.2
  - python-openid==2.2.5
  - python-social-auth==0.2.14
  - requests-oauthlib==0.6.2
  - requests-toolbelt==0.7.0
  - scp==0.7.1
  - sqlalchemy==1.0.15
  - tethys-dataset-services==1.5.0
  - tethyscluster==0.1.6
  - websocket-client==0.37.0
  - workerpool==0.9.2

