# environment_py2.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment_py2.yml

name: tethys

channels:
- conda-forge
- defaults

dependencies:
- python=2.7*
- django=1.11.*
- django-filter=1.0*
- djangorestframework=3.6*
- bokeh=0.12*
- future=0.16*
- paste=2.0*
- psycopg2=2.7*
- sqlalchemy=1.1*
- requests=2.18*
- selenium=3.4*
- coverage=4*
- docker-py<1.10
- geoalchemy2=0.4*
- owslib=0.14*
- pip=9.0*
- pillow=4.1*
- plotly=1.12*
- postgresql=9.5*
- pycrypto=2.6*
- pyopenssl=16.2*
- pip:
    - django-gravatar2
    - django-bootstrap3
    - django-model-utils
    - django-guardian
    - django-simple-captcha
    - django-termsandconditions
    - django-session-security
    - tethys_dataset_services
    - condorpy
    - social-auth-app-django
