# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: tethys

channels:
- tethysplatform
- conda-forge
- defaults

dependencies:
- python

# system dependencies
- pycrypto
- pyopenssl
- docker-py
- distro

# database dependencies
- postgresql
- psycopg2
- sqlalchemy
- geoalchemy2

# plotting dependencies
- plotly
- bokeh

# external services dependencies
- tethys_dataset_services>=2.0.0
- hs_restclient
- owslib
- requests
- social-auth-app-django
- dask
- tethys_dask_scheduler>=1.0.2

# django/plugin dependencies
- django=2.1.*
- django-filter
- djangorestframework
- django-bootstrap3
- django-model-utils
- django-guardian

# tests dependencies
- requests-mock
- selenium
- coverage
- factory_boy

# for now
- pillow
- pip
- future
- flake8

# Conda to allow Python API access to Conda Install
- conda
