# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: tethys

channels:
  - conda-forge
  - tethysplatform
  - defaults

dependencies:
  - python

  # encryption dependencies
  - bcrypt

  # spatial dependencies
  - PyShp

  # system dependencies
  - pyopenssl
  - docker-py
  - distro

  # database dependencies
  - postgresql
  - psycopg2
  - sqlalchemy=1.*  # TODO: what will it take to support sqlalchemy 2.0?
  - geoalchemy2

  # plotting dependencies
  - plotly
  - bokeh<3

  # external services dependencies
  - tethys_dataset_services>=2.0.0
  - hs_restclient
  - owslib
  - requests
  - dask
  - tethys_dask_scheduler>=1.0.2
  - service_identity
  - condorpy
  - siphon
  - python-jose
  - pyjwt

  # datetime dependencies
  - arrow
  - isodate

  # django/plugin dependencies
  - django=3.2.*
  - channels=3.*
  - daphne=3.*
  - django-analytical
  - django-axes
  - django-filter
  - djangorestframework
  - django-bootstrap5
  - django-cors-headers
  - django-model-utils
  - django-guardian
  - django-gravatar2
  - django-json-widget
  - django-mfa2
  - django-recaptcha2
  - django-simple-captcha
  - django-session-security
  - django-termsandconditions
  - social-auth-app-django

  # tests dependencies
  - selenium
  - coverage
  - factory_boy

  # for now
  - pillow
  - pip
  - future
  - flake8
  - flake8-bugbear
  - git
  - setuptools_scm
  - openssl

  # Conda to allow Python API access to Conda Install
  - conda
  - conda-libmamba-solver
