version: '3.1'

services:
  db:
    image: postgis/postgis
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mysecretpassword

  tethys:
    image: tethysplatform/tethys-dev
    user: "${UID_GID}"
    volumes:
    - .:/tethysdev
    ports:
    - "8000:8000"
    depends_on:
    - db